class Nav:
    INITIALISE = "Initialise"
    MAIN_MENU = "Main Menu"
    RETIME = "Retime"
    ANALYSE = "Analyse"
    IMPORT = "Import"
    DECKS = "Decks"
    REVIEW = "Review"
    SETTINGS = "Settings"
    HELP = "Help"
